version: "3.9"

services:
  video-bot:
    build: .
    container_name: video_bot
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./edited:/app/edited
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
